
package com.tqw.upms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T20:49:40.860+08:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "ITIAppException", targetNamespace = "http://immd.itifwk.util/v1")
public class ITIAppException_Exception extends Exception {

    private ITIAppException itiAppException;

    public ITIAppException_Exception() {
        super();
    }

    public ITIAppException_Exception(String message) {
        super(message);
    }

    public ITIAppException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ITIAppException_Exception(String message, ITIAppException itiAppException) {
        super(message);
        this.itiAppException = itiAppException;
    }

    public ITIAppException_Exception(String message, ITIAppException itiAppException, Throwable cause) {
        super(message, cause);
        this.itiAppException = itiAppException;
    }

    public ITIAppException getFaultInfo() {
        return this.itiAppException;
    }
}
