
package com.tqw.upms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T20:49:40.896+08:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "ITISysException", targetNamespace = "http://immd.itifwk.util/v1")
public class ITISysException_Exception extends Exception {

    private ITISysException itiSysException;

    public ITISysException_Exception() {
        super();
    }

    public ITISysException_Exception(String message) {
        super(message);
    }

    public ITISysException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ITISysException_Exception(String message, ITISysException itiSysException) {
        super(message);
        this.itiSysException = itiSysException;
    }

    public ITISysException_Exception(String message, ITISysException itiSysException, Throwable cause) {
        super(message, cause);
        this.itiSysException = itiSysException;
    }

    public ITISysException getFaultInfo() {
        return this.itiSysException;
    }
}
