package com.tqw.upms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-07T20:05:23.586+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://immd.upms.ws/v1", name = "LDAPImmdUserServiceExtWS")
@XmlSeeAlso({ObjectFactory.class})
public interface LDAPImmdUserServiceExtWS {

    @WebMethod
    @RequestWrapper(localName = "getCurrentlySignOnUserByLocId", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.GetCurrentlySignOnUserByLocId")
    @ResponseWrapper(localName = "getCurrentlySignOnUserByLocIdResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.GetCurrentlySignOnUserByLocIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<UserSimpleDetailDTO> getCurrentlySignOnUserByLocId(
            @WebParam(name = "locID", targetNamespace = "")
                    String locID,
            @WebParam(name = "isWithUserDetail", targetNamespace = "")
                    Boolean isWithUserDetail
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "invalidUserLogin", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.InvalidUserLogin")
    @ResponseWrapper(localName = "invalidUserLoginResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.InvalidUserLoginResponse")
    public void invalidUserLogin(
            @WebParam(name = "errorCode", targetNamespace = "")
                    String errorCode,
            @WebParam(name = "errorMsg", targetNamespace = "")
                    String errorMsg
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getCurrentlySignOnUserByLocIdBySysIdResponse", targetNamespace = "http://immd.upms.ws/v1", partName = "parameters")
    public GetCurrentlySignOnUserByLocIdBySysIdResponse getCurrentlySignOnUserByLocIdBySysId(
            @WebParam(partName = "parameters", name = "getCurrentlySignOnUserByLocIdBySysId", targetNamespace = "http://immd.upms.ws/v1")
                    GetCurrentlySignOnUserByLocIdBySysId parameters,
            @WebParam(partName = "appInfo", name = "appInfo", targetNamespace = "http://immd.upms.ws/v1", header = true)
                    AppUserInfoHeader appInfo
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "userDetailEnquiry", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.UserDetailEnquiry")
    @ResponseWrapper(localName = "userDetailEnquiryResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.UserDetailEnquiryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Iss3UserDTO userDetailEnquiry(
            @WebParam(name = "immdToken", targetNamespace = "")
                    String immdToken
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "validateImmdToken", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.ValidateImmdToken")
    @ResponseWrapper(localName = "validateImmdTokenResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.ValidateImmdTokenResponse")
    public void validateImmdToken(
            @WebParam(name = "immdToken", targetNamespace = "")
                    String immdToken
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.ChangePasswordResponse")
    public void changePassword(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "hashedCurrentPassword", targetNamespace = "")
                    String hashedCurrentPassword,
            @WebParam(name = "hashedNewPassword", targetNamespace = "")
                    String hashedNewPassword
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "forceLogout", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.ForceLogout")
    @ResponseWrapper(localName = "forceLogoutResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.ForceLogoutResponse")
    public void forceLogout(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "userAuthenticate", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.UserAuthenticate")
    @ResponseWrapper(localName = "userAuthenticateResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.UserAuthenticateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Iss3UserSignOnDTO userAuthenticate(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "hashedPassword", targetNamespace = "")
                    String hashedPassword,
            @WebParam(name = "terminalID", targetNamespace = "")
                    String terminalID
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setSessionExpiry", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.SetSessionExpiry")
    @ResponseWrapper(localName = "setSessionExpiryResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.SetSessionExpiryResponse")
    public void setSessionExpiry(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "immdToken", targetNamespace = "")
                    String immdToken,
            @WebParam(name = "sessionExpiryDate", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar sessionExpiryDate
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getUserListByRoleCdAndLocId", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.GetUserListByRoleCdAndLocId")
    @ResponseWrapper(localName = "getUserListByRoleCdAndLocIdResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.GetUserListByRoleCdAndLocIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<UserPwd> getUserListByRoleCdAndLocId(
            @WebParam(name = "roleCds", targetNamespace = "")
                    java.util.List<String> roleCds,
            @WebParam(name = "locIDs", targetNamespace = "")
                    java.util.List<String> locIDs
    ) throws ITIAppException_Exception, ITISysException_Exception;
}
