package com.tqw.upms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T20:49:40.906+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://immd.upms.ws/v1", name = "RoleProfileExtWS")
@XmlSeeAlso({ObjectFactory.class})
public interface RoleProfileExtWS {

    @WebMethod
    @RequestWrapper(localName = "enquireUserRole", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.EnquireUserRole")
    @ResponseWrapper(localName = "enquireUserRoleResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.EnquireUserRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<RoleDTO> enquireUserRole(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "enquireTerminalRole", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.EnquireTerminalRole")
    @ResponseWrapper(localName = "enquireTerminalRoleResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.EnquireTerminalRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<RoleDTO> enquireTerminalRole(
            @WebParam(name = "terminalID", targetNamespace = "")
                    String terminalID
    ) throws ITIAppException_Exception, ITISysException_Exception;

    @WebMethod
    @RequestWrapper(localName = "enquireRoleProfile", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.EnquireRoleProfile")
    @ResponseWrapper(localName = "enquireRoleProfileResponse", targetNamespace = "http://immd.upms.ws/v1", className = "com.scw.upms.EnquireRoleProfileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<RoleDTO> enquireRoleProfile(
            @WebParam(name = "roleList", targetNamespace = "")
                    java.util.List<String> roleList,
            @WebParam(name = "systemID", targetNamespace = "")
                    String systemID
    ) throws ITIAppException_Exception, ITISysException_Exception;
}
