package com.tqw.upms;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T20:49:40.923+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "RoleProfileExtWS",
                  wsdlLocation = "file:./roleProfileExtWS.wsdl",
                  targetNamespace = "http://immd.upms.ws/v1")
public class RoleProfileExtWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://immd.upms.ws/v1", "RoleProfileExtWS");
    public final static QName RoleProfileExtWSImplPort = new QName("http://immd.upms.ws/v1", "RoleProfileExtWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:./roleProfileExtWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RoleProfileExtWS_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:./roleProfileExtWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RoleProfileExtWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoleProfileExtWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleProfileExtWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RoleProfileExtWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RoleProfileExtWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RoleProfileExtWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RoleProfileExtWS
     */
    @WebEndpoint(name = "RoleProfileExtWSImplPort")
    public RoleProfileExtWS getRoleProfileExtWSImplPort() {
        return super.getPort(RoleProfileExtWSImplPort, RoleProfileExtWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleProfileExtWS
     */
    @WebEndpoint(name = "RoleProfileExtWSImplPort")
    public RoleProfileExtWS getRoleProfileExtWSImplPort(WebServiceFeature... features) {
        return super.getPort(RoleProfileExtWSImplPort, RoleProfileExtWS.class, features);
    }

}
